[package]
name = "loader"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
windows_wrapper = { workspace = true }
windows = { version = "0.62.2", features = ["Win32_Storage_FileSystem"] }
rfd = "0.16.0"
